import event


class Ticket:
    """
    Instance class Ticket have all information about Event and status of the Customer. Also, Ticket have unique
    serial number.
    """

    def __init__(self, event_inst: event.Event, serial_number, price: int, type_of_ticket: str, sale_time: str):
        """

        :param event_inst: Instance class Event.
        :param serial_number: Serial number of the Ticket, generated by MarketPlace.
        :param price: Price of the Ticket.
        :param type_of_ticket: On of 4 types of Ticket: regular, advance, late, student.
        """
        self.name = event_inst.name
        self.date = str(event_inst.date)[:-9]
        self.time = event_inst.time
        self.location = event_inst.location
        self.price = price
        self.type = type_of_ticket
        self.serial_number = serial_number
        self.sale_time = sale_time

    def __str__(self):
        """

        :return: String vision of Ticket.
        """
        return f"""
Event name - {self.name}
Event date - {self.date}
Event time - {self.time}
Event location - {self.location}
Ticket price - {self.price}
Ticket type - {self.type}

Sale time - {self.sale_time}
Serial number - {self.serial_number}"""
